import { Card } from "./state";

export const cards: Card[] = [
  {
    id: "alluring-narwhal",
    image: "/images/cards/alluring.png",
    name: "Alluring Narwhal",
    type: "UNICORN",
    unifornCount: 1,
    description:
      "When this card enters your Stable, you may move an upgrade card from any player's Stable to your Stable",
  },
  {
    id: "americorn",
    unifornCount: 1,
    description: "test",
    type: "UNICORN",
    image: "/images/cards/americorn.png",
    name: "Americon",
    event: { variant: "CARD_HAND" },
  },
  {
    id: "annoying-flying-unicorn",
    image: "/images/cards/annoying.png",
    name: "Annoying flying unicorn",
    description: "",
    unifornCount: 1,
    type: "UNICORN",
    event: {
      variant: "CHOOSE_PLAYER",
    },
  },
  {
    id: "back-kick",
    image: "/images/cards/backkick.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "barbed-wire",
    image: "/images/cards/barbedwire.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "basic-unicorn-blue",
    image: "/images/cards/basicblue.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "basic-unicorn-green",
    image: "/images/cards/basicgreen.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "basic-unicorn-indigo",
    image: "/images/cards/basicindigo.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "narwhal",
    image: "/images/cards/basicnarwhal.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "basic-unicorn-orange",
    image: "/images/cards/basicorange.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "basic-unicorn-purple",
    image: "/images/cards/basicpurple.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "basic-unicorn-red",
    image: "/images/cards/basicred.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "basic-unicorn-yellow",
    image: "/images/cards/basicyellow.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "black-knight-unicorn",
    image: "/images/cards/blackknight.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "blatant-thievery",
    image: "/images/cards/blatantthievery.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "blinding-light",
    image: "/images/cards/blindinglight.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "broken-stable",
    image: "/images/cards/brokenstable.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "chainsaw-unicorn",
    image: "/images/cards/chainsaw.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "change-of-luck",
    image: "/images/cards/changeofluck.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "classy-narwhal",
    image: "/images/cards/classynarwhal.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "double-dutch",
    image: "/images/cards/doubledutch.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "extra-tail",
    image: "/images/cards/extratail.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "ginormous-unicorn",
    image: "/images/cards/ginormous.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "glitter-bomb",
    image: "/images/cards/glitterbomb.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "glitter-tornado",
    image: "/images/cards/glittertornado.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "good-deal",
    image: "/images/cards/gooddeal.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "greedy-flying-unicorn",
    image: "/images/cards/greedyflying.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "magical-flying-unicorn",
    image: "/images/cards/magicalflying.jpg",
    name: "",
    description: "",
    type: "UNICORN",
  },
  {
    id: "majestic-flying-unicorn",
    image: "/images/cards/majesticflying.jpg",
    name: "",
    description: "",
    type: "UNICORN",
  },
  {
    id: "mermaid-unicorn",
    image: "/images/cards/mermaid.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "mystical-vortex",
    image: "/images/cards/mysticalvortex.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "nanny-cam",
    image: "/images/cards/nannycam.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "narwhal-torpedo",
    image: "/images/cards/narwhaltorpedo.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "neigh",
    image: "/images/cards/neigh.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "pandamonium",
    image: "/images/cards/pandamonium.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "puppicorn",
    image: "/images/cards/puppicorn.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "queen-bee-unicorn",
    image: "/images/cards/queenbee.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "rainbow-aura",
    image: "/images/cards/rainbowaura.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "rainbow-mane",
    image: "/images/cards/rainbowmane.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "rainbow-unicorn",
    image: "/images/cards/rainbow.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "re-target",
    image: "/images/cards/retarget.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "reset-button",
    image: "/images/cards/resetbutton.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "rhinocorn",
    image: "/images/cards/rhinocorn.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "sadistic-ritual",
    image: "/images/cards/sadisticritual.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "seductive-unicorn",
    image: "/images/cards/seductive.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "shabby-the-narwhal",
    image: "/images/cards/shabby.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "shake-up",
    image: "/images/cards/shakeup.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "shark-with-a-horn",
    image: "/images/cards/sharkwithahorn.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "slowdown",
    image: "/images/cards/slowdown.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "stabby-the-unicorn",
    image: "/images/cards/stabby.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "summoning-ritual",
    image: "/images/cards/summoningritual.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "super-neigh",
    image: "/images/cards/UU-ChCo-001.png",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "swift-flying-unicorn",
    image: "/images/cards/swiftflying.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "targeted-destruction",
    image: "/images/cards/targeteddestruction.jpg",
    name: "",
    description: "",
    type: "UNICORN",
  },
  {
    id: "the-great-narwhal",
    image: "/images/cards/thegreatnarwhal.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "tiny-stable",
    image: "/images/cards/tinystable.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "two-for-one",
    image: "/images/cards/twoforone.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "unfair-bargain",
    image: "/images/cards/unfairbargain.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "unicorn-lasso",
    image: "/images/cards/unicornlasso.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "unicorn-on-the-cob",
    image: "/images/cards/unicornonthecob.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "unicorn-poison",
    image: "/images/cards/unicornpoison.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "unicorn-shrinkray",
    image: "/images/cards/unicornshrinkray.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "unicorn-swap",
    image: "/images/cards/unicornswap.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "yay",
    image: "/images/cards/yay.jpg",
    description: "",
    name: "",
    type: "UNICORN",
    unifornCount: 1,
  },
];

export const reversedCards = cards.reverse();

export const nusery: Card[] = [
  {
    id: "baby-narwhal",
    image: "/images/cards/babynarwhal.jpg",
    name: "Baby",
    description: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "baby-unicorn-black",
    image: "/images/cards/babyblack.jpg",
    name: "Baby",
    description: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "baby-unicorn-blue",
    image: "/images/cards/babyblue.jpg",
    name: "Baby",
    description: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "baby-unicorn-brown",
    image: "/images/cards/babybrown.jpg",
    name: "Baby",
    description: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "baby-unicorn-death",
    image: "/images/cards/babydeath.jpg",
    name: "Baby",
    description: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "baby-unicorn-green",
    image: "/images/cards/babygreen.jpg",
    name: "Baby",
    description: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "baby-unicorn-orange",
    image: "/images/cards/babyorange.jpg",
    name: "Baby",
    description: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "baby-unicorn-pink",
    image: "/images/cards/babypink.jpg",
    name: "Baby",
    description: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "baby-unicorn-purple",
    image: "/images/cards/babypurple.jpg",
    name: "Baby",
    description: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "baby-unicorn-rainbow",
    image: "/images/cards/babyrainbow.jpg",
    name: "Baby",
    description: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "baby-unicorn-white",
    image: "/images/cards/babywhite.jpg",
    name: "Baby",
    description: "",
    type: "UNICORN",
    unifornCount: 1,
  },
  {
    id: "baby-unicorn-yellow",
    image: "/images/cards/babyyellow.jpg",
    name: "Baby",
    description: "",
    type: "UNICORN",
    unifornCount: 1,
  },
];
